# Generated by Django 4.2.5 on 2023-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Description',
            field=models.CharField(max_length=500, null=True, verbose_name='Desc'),
        ),
    ]
