# Generated by Django 4.2.5 on 2024-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0002_jobs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
            ],
        ),
    ]
