# Generated by Django 4.2.5 on 2024-02-26 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='student',
            name='Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
