# Generated by Django 4.2.5 on 2024-02-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0004_remove_student_studentid_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
