# Generated by Django 4.2.5 on 2024-02-26 06:19

import cmrs_web_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', cmrs_web_app.models.RollNumberField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{2}JJ[15]A\\d{4}$')])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
