# Generated by Django 4.2.5 on 2024-03-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='BackLogCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Gap',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tenthCGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelthPercentage',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='UserDefinedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(max_length=200)),
                ('github_repo_url', models.URLField(blank=True)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsibilities', models.TextField()),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student')),
            ],
        ),
    ]
