# Generated by Django 4.2.5 on 2024-03-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0007_student_backlogcount_student_gap_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='responsibilities',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('skills', models.CharField(max_length=200)),
                ('domain_technology', models.CharField(max_length=100)),
                ('year_earned', models.DateField()),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student')),
            ],
        ),
    ]
