# Generated by Django 4.2.5 on 2024-04-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0008_alter_internship_responsibilities_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='roll_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student'),
        ),
    ]
