# Generated by Django 4.2.5 on 2024-04-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0009_users_password_users_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
