# Generated by Django 4.2.5 on 2024-04-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0016_remove_importantdates_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhaseNo', models.IntegerField(null=True)),
                ('PhaseTitle', models.CharField(max_length=50, null=True)),
                ('PhaseFeedback', models.TextField(null=True)),
                ('Rating', models.IntegerField(null=True)),
                ('DifficultyLevel', models.CharField(max_length=50, null=True)),
                ('Suggestions', models.TextField(null=True)),
                ('WouldRecommend', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.jobs')),
                ('RollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.student')),
                ('imp_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmrs_web_app.importantdates')),
            ],
            options={
                'unique_together': {('Job', 'RollNumber', 'PhaseNo')},
            },
        ),
    ]
