# Generated by Django 4.2.5 on 2024-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0017_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C.S.E', 'Computer Science and Engineering'), ('E.E.E', 'Electrical and Electronics Engineering'), ('I.T', 'Information Technology'), ('M.E.', 'Mechanical Engineering'), ('E.C.E', 'Electronics and Communication Engineering')], max_length=100)),
                ('departmentHead', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
