# Generated by Django 4.2.5 on 2024-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0018_branch_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='max_backlog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='min_cgpa',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='min_tenth_cgpa',
            field=models.FloatField(default=7.0, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='min_twelth_percentage',
            field=models.FloatField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='no_gap_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='skills_required',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
