# Generated by Django 4.2.5 on 2024-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0019_alter_eligibilitycriteria_max_backlog_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='APPLIED', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='batchYear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('IT', 'IT'), ('ME.', 'ME'), ('ECE', 'ECE')], default='CSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('IT', 'IT'), ('ME.', 'ME'), ('ECE', 'ECE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='skills_required',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
