# Generated by Django 4.2.5 on 2024-04-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0020_application_status_student_batchyear_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeedback',
            options={'ordering': ['-imp_date', 'RollNumber']},
        ),
        migrations.AlterUniqueTogether(
            name='studentfeedback',
            unique_together={('imp_date', 'RollNumber')},
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='DifficultyLevel',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='PhaseNo',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='PhaseTitle',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='Suggestions',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='WouldRecommend',
        ),
    ]
