# Generated by Django 4.2.5 on 2024-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0021_alter_studentfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_gap',
            field=models.BooleanField(default=False),
        ),
    ]
