# Generated by Django 4.2.5 on 2024-04-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0022_student_year_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Gap',
        ),
    ]
