# Generated by Django 4.2.5 on 2024-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrs_web_app', '0023_remove_student_gap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-job', '-application_date']},
        ),
        migrations.AddField(
            model_name='application',
            name='batchYear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='application',
            name='branch',
            field=models.CharField(default='CSE', max_length=5),
        ),
    ]
